### ISSUE TITLE
How to map credential subject data into proper string?

### ISSUE THREAD

**Issue by bibash28** [iden3/claim-schema-vocab#25]
For example:
```
credentialSubject": {
            "countryCode": {
              "$nin": [
                840,
                120,
                340,
                509
              ]
            }
          }
```
into 
![image](https://user-images.githubusercontent.com/18188709/235649979-58d117b1-1b09-41bc-bb44-007fa29cbe42.png)

**Comment by vladyslavmunin** [comment]
can you provide more info for this issue? As I understood this is an example of proof request. And how does it related to schema of KYCCountryOfResidenceCredential?

Nin operator can give the label 'is not one of the following values' if you develop some wallet.

**Comment by bibash28** [comment]
Yes, $nin is understandable. But we don't know if there are other such parameters we can get in response. So, we need something that can directly convert such strings into readable texts as in the screenshot provided.

**Comment by vmidyllic** [comment]
right now only a set of primitive operators is supported:
$in $nin $eq $lt $gt $noop.
text to display in the wallet is app-specific and is not linked to operators.
We work on opportunity to give context to request , so in future it can be possible to give metadata about operators.
